/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BillingRouteImport } from './routes/billing'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as TalkRouteImport } from './routes/talk'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as DashboardBillingRouteImport } from './routes/dashboard.billing'
import { Route as DashboardDocumentsRouteImport } from './routes/dashboard.documents'
import { Route as DashboardHistoryRouteImport } from './routes/dashboard.history'
import { Route as ApiRazorpayWebhookRouteImport } from './routes/api.razorpay.webhook'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BillingRoute = BillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const TalkRoute = TalkRouteImport.update({
  id: '/talk',
  path: '/talk',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardBillingRoute = DashboardBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardDocumentsRoute = DashboardDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardHistoryRoute = DashboardHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => DashboardRoute,
} as any)
const ApiRazorpayWebhookRoute = ApiRazorpayWebhookRouteImport.update({
  id: '/api/razorpay/webhook',
  path: '/api/razorpay/webhook',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/billing': typeof BillingRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/history': typeof HistoryRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/talk': typeof TalkRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/dashboard/billing': typeof DashboardBillingRoute
  '/dashboard/documents': typeof DashboardDocumentsRoute
  '/dashboard/history': typeof DashboardHistoryRoute
  '/api/razorpay/webhook': typeof ApiRazorpayWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/billing': typeof BillingRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/history': typeof HistoryRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/talk': typeof TalkRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/dashboard/billing': typeof DashboardBillingRoute
  '/dashboard/documents': typeof DashboardDocumentsRoute
  '/dashboard/history': typeof DashboardHistoryRoute
  '/api/razorpay/webhook': typeof ApiRazorpayWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/billing': typeof BillingRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/history': typeof HistoryRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/talk': typeof TalkRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/dashboard/billing': typeof DashboardBillingRoute
  '/dashboard/documents': typeof DashboardDocumentsRoute
  '/dashboard/history': typeof DashboardHistoryRoute
  '/api/razorpay/webhook': typeof ApiRazorpayWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/billing'
    | '/dashboard'
    | '/history'
    | '/login'
    | '/privacy'
    | '/signup'
    | '/sitemap.xml'
    | '/talk'
    | '/auth/callback'
    | '/dashboard/billing'
    | '/dashboard/documents'
    | '/dashboard/history'
    | '/api/razorpay/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/billing'
    | '/dashboard'
    | '/history'
    | '/login'
    | '/privacy'
    | '/signup'
    | '/sitemap.xml'
    | '/talk'
    | '/auth/callback'
    | '/dashboard/billing'
    | '/dashboard/documents'
    | '/dashboard/history'
    | '/api/razorpay/webhook'
  id:
    | '__root__'
    | '/'
    | '/billing'
    | '/dashboard'
    | '/history'
    | '/login'
    | '/privacy'
    | '/signup'
    | '/sitemap.xml'
    | '/talk'
    | '/auth/callback'
    | '/dashboard/billing'
    | '/dashboard/documents'
    | '/dashboard/history'
    | '/api/razorpay/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BillingRoute: typeof BillingRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  HistoryRoute: typeof HistoryRoute
  LoginRoute: typeof LoginRoute
  PrivacyRoute: typeof PrivacyRoute
  SignupRoute: typeof SignupRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TalkRoute: typeof TalkRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  ApiRazorpayWebhookRoute: typeof ApiRazorpayWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/billing': {
      id: '/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof BillingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/talk': {
      id: '/talk'
      path: '/talk'
      fullPath: '/talk'
      preLoaderRoute: typeof TalkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/billing': {
      id: '/dashboard/billing'
      path: '/billing'
      fullPath: '/dashboard/billing'
      preLoaderRoute: typeof DashboardBillingRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/documents': {
      id: '/dashboard/documents'
      path: '/documents'
      fullPath: '/dashboard/documents'
      preLoaderRoute: typeof DashboardDocumentsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/history': {
      id: '/dashboard/history'
      path: '/history'
      fullPath: '/dashboard/history'
      preLoaderRoute: typeof DashboardHistoryRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/api/razorpay/webhook': {
      id: '/api/razorpay/webhook'
      path: '/api/razorpay/webhook'
      fullPath: '/api/razorpay/webhook'
      preLoaderRoute: typeof ApiRazorpayWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface DashboardRouteChildren {
  DashboardBillingRoute: typeof DashboardBillingRoute
  DashboardDocumentsRoute: typeof DashboardDocumentsRoute
  DashboardHistoryRoute: typeof DashboardHistoryRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardBillingRoute: DashboardBillingRoute,
  DashboardDocumentsRoute: DashboardDocumentsRoute,
  DashboardHistoryRoute: DashboardHistoryRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BillingRoute: BillingRoute,
  DashboardRoute: DashboardRouteWithChildren,
  HistoryRoute: HistoryRoute,
  LoginRoute: LoginRoute,
  PrivacyRoute: PrivacyRoute,
  SignupRoute: SignupRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TalkRoute: TalkRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  ApiRazorpayWebhookRoute: ApiRazorpayWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
